# Site settings
title: "Useless Blag"
email: ""
description: ""
baseurl: ""
url: "https://mrdaveanderson.github.io/"
title_description: "A blog of random tech stuff"
#title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
#title_image: "https://pbs.twimg.com/profile_images/1471367360/leopard-glass-power-off-button_128x128.png"
title_image: "/images/PowerIcon-256.png"
#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
#github_repository: https://github.com/jacobtomlinson/carte-noire
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _mrdaveandrson
github_username:  mrdaveanderson
#linkedin_link: 
#google_plus_link: 
#stackoverflow_link: 

# Footer
footer_left: "Jekyll <a href=\"https://github.com/jacobtomlinson/carte-noire\">page theme</a> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "My <a href=\"https://github.com/mrdaveanderson\">Github</a> Projects"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
