# Site settings
title: "Useless Blag"
email: ""
description: ""
baseurl: ""
url: "https://mrdaveanderson.github.io/"
title_description: "A blog of random tech stuff"
title_image: "/images/PowerIcon-256.png"
post_limit: 8

# Social usernames/URLs
twitter_username: "mrdaveanderson"
github_username: "mrdaveanderson"

# Footer
footer_left: "Jekyll <a href=\"https://github.com/jacobtomlinson/carte-noire\">page theme</a> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "My <a href=\"https://github.com/mrdaveanderson\">Github</a> Projects"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
